`define MODULE_NAME FFT_Top
`define FIXED
`define FFT256
`define POINTS 256
`define POINTS_LOG 8
`define TARGET_DEVICE_GW5AT
`define LOW_RESOURCE
`define MODE_FORWARD
`define OUTPUT_NATURAL
`define SCALING_RS111
`define INPUT_DATA_WIDTH 16
`define INPUT_DATA_WIDTH_LOG 4
`define TWIDDLE_FACTOR_WIDTH 16
`define TWIDDLE_FACTOR_WIDTH_LOG 4
`define OUTPUT_DATA_WIDTH 16
`define OUTPUT_DATA_WIDTH_LOG 4
`define REDUCTION_TRUNCATION
`define DSP_BLOCK_BASED
`define EBR_MEMORY
`define TDF_EBR_MEMORY
